pet_tracker/lib/pet_tracker_web/router.ex
defmodule PetTrackerWeb.Router do
  use PetTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PetTrackerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PetTrackerWeb do
    pipe_through :browser

    live "/", OwnerLive.Index, :index

    live "/owners", OwnerLive.Index, :index
    live "/owners/new", OwnerLive.Index, :new
    live "/owners/:id/edit", OwnerLive.Index, :edit

    live "/owners/:id", OwnerLive.Show, :show
    live "/owners/:id/show/edit", OwnerLive.Show, :edit

    live "/pets", PetLive.Index, :index
    live "/pets/new", PetLive.Index, :new
    live "/pets/:id/edit", PetLive.Index, :edit

    live "/pets/:id", PetLive.Show, :show
    live "/pets/:id/show/edit", PetLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", PetTrackerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PetTrackerWeb.Telemetry
    end
  end
end

pet_tracker/lib/pet_tracker_web/live/live_helpers.ex
defmodule PetTrackerWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `PetTrackerWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, PetTrackerWeb.OwnerLive.FormComponent,
        id: @owner.id || :new,
        action: @live_action,
        owner: @owner,
        return_to: Routes.owner_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, PetTrackerWeb.ModalComponent, modal_opts)
  end
end

pet_tracker/lib/pet_tracker_web/live/modal_component.ex
defmodule PetTrackerWeb.ModalComponent do
  use PetTrackerWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

pet_tracker/lib/pet_tracker_web/live/owner_live/form_component.ex
defmodule PetTrackerWeb.OwnerLive.FormComponent do
  use PetTrackerWeb, :live_component

  alias PetTracker.Tracker

  @impl true
  def update(%{owner: owner} = assigns, socket) do
    changeset = Tracker.change_owner(owner)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"owner" => owner_params}, socket) do
    changeset =
      socket.assigns.owner
      |> Tracker.change_owner(owner_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"owner" => owner_params}, socket) do
    save_owner(socket, socket.assigns.action, owner_params)
  end

  defp save_owner(socket, :edit, owner_params) do
    case Tracker.update_owner(socket.assigns.owner, owner_params) do
      {:ok, _owner} ->
        {:noreply,
         socket
         |> put_flash(:info, "Owner updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_owner(socket, :new, owner_params) do
    case Tracker.create_owner(owner_params) do
      {:ok, _owner} ->
        {:noreply,
         socket
         |> put_flash(:info, "Owner created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

pet_tracker/lib/pet_tracker_web/live/owner_live/index.ex
defmodule PetTrackerWeb.OwnerLive.Index do
  use PetTrackerWeb, :live_view

  alias PetTracker.Tracker
  alias PetTracker.Tracker.Owner

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :owners, list_owners())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Owner")
    |> assign(:owner, Tracker.get_owner!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Owner")
    |> assign(:owner, %Owner{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Owners")
    |> assign(:owner, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    owner = Tracker.get_owner!(id)
    {:ok, _} = Tracker.delete_owner(owner)

    {:noreply, assign(socket, :owners, list_owners())}
  end

  defp list_owners do
    Tracker.list_owners()
  end
end

pet_tracker/lib/pet_tracker_web/live/owner_live/show.ex
defmodule PetTrackerWeb.OwnerLive.Show do
  use PetTrackerWeb, :live_view

  alias PetTracker.Tracker

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:owner, Tracker.get_owner!(id))}
  end

  defp page_title(:show), do: "Show Owner"
  defp page_title(:edit), do: "Edit Owner"
end

pet_tracker/lib/pet_tracker_web/live/page_live.ex
defmodule PetTrackerWeb.PageLive do
  use PetTrackerWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not PetTrackerWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

pet_tracker/lib/pet_tracker_web/live/pet_live/form_component.ex
defmodule PetTrackerWeb.PetLive.FormComponent do
  use PetTrackerWeb, :live_component

  alias PetTracker.Tracker

  @impl true
  def update(%{pet: pet} = assigns, socket) do
    changeset = Tracker.change_pet(pet)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"pet" => pet_params}, socket) do
    changeset =
      socket.assigns.pet
      |> Tracker.change_pet(pet_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"pet" => pet_params}, socket) do
    save_pet(socket, socket.assigns.action, pet_params)
  end

  defp save_pet(socket, :edit, pet_params) do
    case Tracker.update_pet(socket.assigns.pet, pet_params) do
      {:ok, _pet} ->
        {:noreply,
         socket
         |> put_flash(:info, "Pet updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_pet(socket, :new, pet_params) do
    case Tracker.create_pet(pet_params) do
      {:ok, _pet} ->
        {:noreply,
         socket
         |> put_flash(:info, "Pet created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

pet_tracker/lib/pet_tracker_web/live/pet_live/index.ex
defmodule PetTrackerWeb.PetLive.Index do
  use PetTrackerWeb, :live_view

  alias PetTracker.Tracker
  alias PetTracker.Tracker.Pet

  @impl true
  def mount(_params, _session, socket) do
    {
      :ok,
      assign(socket, :pets, list_pets()),
      temporary_assigns: [
        select: Tracker.owners_select_opts(),
        owners: Tracker.list_owners()
      ]
    }
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Pet")
    |> assign(:pet, Tracker.get_pet!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Pet")
    |> assign(:pet, %Pet{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Pets")
    |> assign(:pet, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    pet = Tracker.get_pet!(id)
    {:ok, _} = Tracker.delete_pet(pet)

    {:noreply, assign(socket, :pets, list_pets())}
  end

  defp list_pets do
    Tracker.list_pets()
  end
end

pet_tracker/lib/pet_tracker_web/live/pet_live/show.ex
defmodule PetTrackerWeb.PetLive.Show do
  use PetTrackerWeb, :live_view

  alias PetTracker.Tracker

  @impl true
  def mount(_params, _session, socket) do
    {
      :ok,
      socket,
      temporary_assigns: [
        select: Tracker.owners_select_opts(),
        owners: Tracker.list_owners()
      ]
    }
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:pet, Tracker.get_pet!(id))}
  end

  defp page_title(:show), do: "Show Pet"
  defp page_title(:edit), do: "Edit Pet"

end

pet_tracker/lib/pet_tracker_web/live/pet_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "pet-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :type %>
  <%= text_input f, :type %>
  <%= error_tag f, :type %>

  <%= label f, :age %>
  <%= number_input f, :age %>
  <%= error_tag f, :age %>

  <%= label f, :owner %>
  <%= select f, :owner, @select %>
  <%= error_tag f, :owner %>

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

pet_tracker/lib/pet_tracker_web/live/pet_live/index.html.leex
<h1>Listing Pets</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, PetTrackerWeb.PetLive.FormComponent,
    id: @pet.id || :new,
    title: @page_title,
    action: @live_action,
    pet: @pet,
    select: @select,
    return_to: Routes.pet_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Age</th>
      <th>Owner</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="pets">
    <%= for pet <- @pets do %>
      <tr id="pet-<%= pet.id %>">
        <td><%= pet.name %></td>
        <td><%= pet.type %></td>
        <td><%= pet.age %></td>
        <td>
          <%= for owner <- @owners do %>
            <%= if owner.id == pet.owner do %>
              <%= owner.lastName %>, <%= owner.firstName %>
            <% end %>
          <% end %>
        </td>

        <td>
          <span><%= live_redirect "Show", to: Routes.pet_show_path(@socket, :show, pet) %></span>
          <span><%= live_patch "Edit", to: Routes.pet_index_path(@socket, :edit, pet) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: pet.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Pet", to: Routes.pet_index_path(@socket, :new) %></span>

pet_tracker/lib/pet_tracker_web/live/pet_live/show.html.leex
<h1>Show Pet</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, PetTrackerWeb.PetLive.FormComponent,
    id: @pet.id,
    title: @page_title,
    action: @live_action,
    pet: @pet,
    select: @select,
    return_to: Routes.pet_show_path(@socket, :show, @pet) %>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @pet.name %>
  </li>

  <li>
    <strong>Type:</strong>
    <%= @pet.type %>
  </li>

  <li>
    <strong>Age:</strong>
    <%= @pet.age %>
  </li>

  <li>
    <strong>Owner</strong>
    <%= for owner <- @owners do %>
      <%= if owner.id == @pet.owner do %>
        <%= owner.firstName %> <%= owner.lastName %>
      <% end %>
    <% end %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.pet_show_path(@socket, :edit, @pet), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.pet_index_path(@socket, :index) %></span>